version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    networks:
      - ishcnet
  ubuntu:
    image: ishcapp
    build: ./
    ports:
      - "3001:3001"
    networks:
      - ishcnet
    depends_on:
      - db
networks:
  ishcnet:
    driver: bridge